version: '3'

services:
  app:
    build:
      context: ./teamdraft_app
      dockerfile: Dockerfile
    container_name: app
    command: sleep infinity
    volumes:
      - ./teamdraft_app:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/td_dev
      - RAILS_ENV=development
    depends_on:
      - db

  # engine:
  #   build:
  #     context: ./teamdraft_engine
  #     dockerfile: Dockerfile
  #   container_name: engine
  #   command: sleep infinity
  #   volumes:
  #     - ./teamdraft_engine:/app
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=td_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
